message=root config

logging:
  level:
    root: debug

---
spring:
  profiles: development

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
