spring:
  profiles:
    active: development

---
spring:
  profiles: development
  

---
spring:
  profiles: vm
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/  
