spring:
  profiles:
    active: development

---
spring:
  profiles: development

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: docker
