spring:
  profiles:
    active: development

---
spring:
  profiles: development
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
zuul:
  routes:
    user-service:
      path: /api/user/**
    todo-service:
      path: /api/todo/**

---
spring:
  profiles: vm
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

zuul:
  routes:
    user-service:
      path: /api/user/**
      url: http://localhost:8082
    todo-service:
      path: /api/todo/**
      url: http://localhost:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${EUREKA_SERVER_PORT:8761}/eureka/
