spring:
  profiles:
    active: development

---
spring:
  profiles: development
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

zuul:
  routes:
    user-service:
      serviceId: user-service  
      path: /api/user/**
    todo-service:
      serviceId: todo-service
      path: /api/todo/**

#user-service:
#  ribbon:
#    listOfServers: http://localhost:8081,http://localhost:8091
    
#todo-service:
#  ribbon:
#    listOfServers: http://localhost:8082,http://localhost:8092,http://localhost:8102

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/   

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: docker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

zuul:
  routes:
    user-service:
      serviceId: user-service  
      path: /api/user/**
    todo-service:
      serviceId: todo-service
      path: /api/todo/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://${DOCKER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
