spring:
  profiles:
    active: development

---
spring:
  profiles: development
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
zuul:
  routes:
    user-service:
      path: /api/user/**
      url: http://gateway:18081
    todo-service:
      path: /api/todo/**
      url: http://gateway:8081

---
spring:
  profiles: vm
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

zuul:
  routes:
    user-service:
      path: /api/user/**
      url: http://gateway:8082
    todo-service:
      path: /api/todo/**
      url: http://gateway:8081
