spring:
  application:
    name: gateway

zuul:
  routes:
    user-service:
      serviceId: user-service  
      path: /user/**
      url: http://localhost:8081

    todo-service:
      serviceId: todo-service
      path: /todo/**
      url: http://localhost:8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
