zuul:
  routes:
    user-service:
      serviceId: user-service  
      path: /uua/**
      url: http://localhost:8081      
      stripPrefix: false
      sensitiveHeaders:

    todo-service:
      serviceId: todo-service
      path: /todo/**
      url: http://localhost:8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
