spring:
  application:
    name: gateway

zuul:
  routes:
    user-gateway:
      serviceId: user-service  
      path: /user/**
      url: http://localhost:8081

    todo-service:
      path: /todo/**
      url: http://localhost:8082
      stripPrefix: false
      sensitiveHeaders:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
