message: Hello TODO TEST Service!!!!

spring:
  profiles:
    active: development

---
spring:
  profiles: development
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/      

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
      
---
spring:
  profiles: docker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DOCKER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/      
