spring:
  profiles:
    active: development

---
spring:
  profiles: development
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/

---
spring:
  profiles: docker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DOCKER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
