message: Hello world!!!!

---

spring:
  profiles: dev
  
service:
  layer: User Service (DEV) - Reflash TEST
  
---
  
spring:
  profiles: prod
  
service:
  layer: User Service (PROD) - Reflash TEST
