message: Hello User Service!!!!

---

spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

service:
  layer: User Service (DEV) - Reflash TEST
  
---
  
spring:
  profiles: prod
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

service:
  layer: User Service (PRODUCTION) - Reflash BUS TEST Again
