message: Hello USER TEST Service!!!!

spring:
  profiles:
    active: development

---
spring:
  profiles: development
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/

---
spring:
  profiles: vm
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/
